# Spring Base Application properties
spring.application.name=asapp-tasks-service

# Config properties
spring.cloud.config.password=${CONFIG_PASSWORD}
spring.cloud.config.username=${CONFIG_USERNAME}
spring.config.import=configserver:http://asapp-config-service:8888/asapp-config-service

# Server properties
server.port=${SERVER_PORT}
server.servlet.context-path=/asapp-tasks-service

# Datasource properties
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}

# Redis properties
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT}

# Liquibase properties
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml
spring.liquibase.contexts=docker
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}

# Management properties
management.server.base-path=${server.servlet.context-path}
management.server.port=${MANAGEMENT_PORT}

# Custom application properties
## Security properties
asapp.security.jwt-secret=${ASAPP_SECURITY_JWT_SECRET}
