# Spring Base Application properties
spring.application.name=asapp-tasks-service

# Config properties
spring.cloud.config.password=${CONFIG_PASSWORD}
spring.cloud.config.username=${CONFIG_USERNAME}

# Server properties
server.port=${SERVER_PORT}
server.servlet.context-path=/asapp-tasks-service

# Security properties
spring.security.user.name=${MANAGEMENT_USERNAME}
spring.security.user.password=${MANAGEMENT_PASSWORD}

# Datasource properties
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}

# Redis properties
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT}

# Liquibase properties
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml
spring.liquibase.contexts=docker
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}

# Eureka properties
eureka.client.service-url.defaultZone=http://${DISCOVERY_USERNAME}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}/eureka
eureka.instance.health-check-url-path=${server.servlet.context-path}/actuator/health
eureka.instance.home-page-url-path=${server.servlet.context-path}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=${server.servlet.context-path}/actuator/info

# Management properties
management.server.base-path=${server.servlet.context-path}
management.server.port=${MANAGEMENT_PORT}

# Custom application properties
## Security properties
asapp.security.jwt-secret=${ASAPP_SECURITY_JWT_SECRET}
