# Spring Base Application properties
spring.application.name=asapp-tasks-service
spring.devtools.livereload.enabled=true

# Spring Config properties
spring.config.import=configserver:http://localhost:8888/asapp-config-service

# Server properties
server.port=8081
server.servlet.context-path=/asapp-tasks-service

# Datasource properties
spring.datasource.url=jdbc:postgresql://localhost:5433/tasksdb
spring.datasource.username=user
spring.datasource.password=secret

# Liquibase properties
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml

# Management properties
management.server.port=8091
management.server.base-path=${server.servlet.context-path}
