# Spring Base Application properties
spring.application.name=asapp-tasks-service
spring.devtools.livereload.enabled=true

# Spring Config properties
spring.cloud.config.password=config-secret
spring.cloud.config.username=config-user
spring.config.import=configserver:http://localhost:8888/asapp-config-service

# Server properties
server.port=8081
server.servlet.context-path=/asapp-tasks-service

# Security properties
spring.security.user.name=tasks-user
spring.security.user.password=tasks-secret

# Datasource properties
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5433/tasksdb
spring.datasource.username=user

# Liquibase properties
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}

# Management properties
management.server.base-path=${server.servlet.context-path}
management.server.port=8091
