# Shared dev configuration for all ASAPP services

# Management properties
management.endpoint.heapdump.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# OpenAPI properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Logger properties
logging.level.com.bcn.asapp=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
