# Shared configuration for all ASAPP services

# Spring Base Application properties
spring.threads.virtual.enabled=true

# Web MVC properties
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# Jackson properties
spring.jackson.default-property-inclusion=NON_NULL

# Redis properties
spring.data.redis.host=localhost
spring.data.redis.password=secret
spring.data.redis.port=6379

# Management properties
management.endpoint.health.cache.time-to-live=30s
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.show-details=when_authorized
management.endpoint.heapdump.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true

# Security properties
asapp.security.jwt-secret=1sgD6PLYh67jSmGqmF1SmrOnGEKw41axyKzeZwnALvFtiOc2tX0E6OBLI0XoFLfL


