# Configuration for asapp-authentication-service

# Logger properties
logging.level.com.bcn.asapp.authentication=INFO
logging.level.org.springframework=INFO

# Custom application properties
## Security properties
asapp.security.access-token.expiration-time=300000
asapp.security.jwt.cleanup.cron-expression=0 0 2 * * ?
asapp.security.jwt.cleanup.enabled=true
asapp.security.refresh-token.expiration-time=3600000
