version: '3.8'
services:
  asapp-tasks-postgres-db:
    image: 'postgres:latest'
    container_name: asapp-tasks-postgres-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=tasksdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - tasks-postgres-db-data:/data/db

  asapp-tasks-service:
    build: .
    image: 'asapp-tasks-service:0.2.0-SNAPSHOT'
    container_name: asapp-tasks-service
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - MANAGEMENT_PORT=8091
      - DB_HOST=asapp-tasks-postgres-db
      - DB_PORT=5432
      - DB_NAME=tasksdb
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - ASAPP_SECURITY_JWT_SECRET=qPxa4PP692Q4fx6voNBX25WoQrzjCoLWLW3VnABjZaOImy0cQaTad5DqBZk3qPxi
    depends_on:
      - asapp-tasks-postgres-db

volumes:
  tasks-postgres-db-data:
