global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'asapp-prometheus:9090' ]
  - job_name: 'asapp-projects-service'
    metrics_path: '/asapp-projects-service/actuator/prometheus'
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/auth/bearer_token
    static_configs:
      - targets: [ 'asapp-projects-service:8090' ]
  - job_name: 'asapp-tasks-service'
    metrics_path: '/asapp-tasks-service/actuator/prometheus'
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/auth/bearer_token
    static_configs:
      - targets: [ 'asapp-tasks-service:8091' ]
  - job_name: 'asapp-authentication-service'
    metrics_path: '/asapp-authentication-service/actuator/prometheus'
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/auth/bearer_token
    static_configs:
      - targets: [ 'asapp-authentication-service:8092' ]
