global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'asapp-prometheus:9090' ]
  - job_name: 'asapp-projects-service'
    metrics_path: '/asapp-projects-service/actuator/prometheus'
    static_configs:
      - targets: [ 'asapp-projects-service:8080' ]
  - job_name: 'asapp-tasks-service'
    metrics_path: '/asapp-tasks-service/actuator/prometheus'
    static_configs:
      - targets: [ 'asapp-tasks-service:8081' ]
  - job_name: 'asapp-uaa-service'
    metrics_path: '/asapp-uaa-service/actuator/prometheus'
    static_configs:
      - targets: [ 'asapp-uaa-service:8082' ]