# Dev configuration for asapp-config-service

# Management properties
management.endpoint.heapdump.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Logger properties
logging.level.com.bcn.asapp=DEBUG
