# Spring Base Application properties
spring.application.name=asapp-config-service
spring.profiles.active=native

# Server properties
server.port=8888
server.servlet.context-path=/asapp-config-service

# Security properties
spring.security.user.name=user
spring.security.user.password=secret

# Config Server properties
spring.cloud.config.server.native.searchLocations=file:///${user.dir}/central-config

# Management properties
management.endpoint.health.cache.time-to-live=30s
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.show-details=when_authorized
management.endpoint.heapdump.access=none
management.endpoint.shutdown.access=none
management.endpoints.web.exposure.include=health,info,prometheus
management.info.env.enabled=false
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true
management.metrics.tags.application=${spring.application.name}
management.server.base-path=${server.servlet.context-path}
management.server.port=8898

# Logger properties
logging.level.org.springframework=INFO
