# Spring Base Application properties
spring.application.name=asapp-users-service
spring.devtools.livereload.enabled=true

# Spring Config properties
spring.cloud.config.password=config-secret
spring.cloud.config.username=config-user
spring.config.import=configserver:http://localhost:8888/asapp-config-service

# Server properties
server.port=8082
server.servlet.context-path=/asapp-users-service

# Datasource properties
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5434/usersdb
spring.datasource.username=user

# Liquibase properties
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}

# Management properties
management.server.base-path=${server.servlet.context-path}
management.server.port=8092

# Custom application properties
## Tasks service client properties
asapp.client.tasks.base-url=http://localhost:8081/asapp-tasks-service
