# Spring Base Application properties
spring.application.name=asapp-users-service
spring.devtools.livereload.enabled=true

# Spring Config properties
spring.cloud.config.password=config-secret
spring.config.import=configserver:${CONFIG_URI:http://localhost:8888/asapp-config-service}
spring.cloud.config.username=config-user

# Server properties
server.port=8082
server.servlet.context-path=/asapp-users-service

# Security properties
spring.security.user.name=users-user
spring.security.user.password=users-secret

# Datasource properties
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5434/usersdb
spring.datasource.username=user

# Liquibase properties
spring.liquibase.change-log=liquibase/db/changelog/db.changelog-master.xml
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}

# Eureka properties
eureka.client.service-url.defaultZone=http://discovery-user:discovery-secret@localhost:8761/asapp-discovery-service/eureka
eureka.instance.health-check-url-path=${server.servlet.context-path}/actuator/health
eureka.instance.home-page-url-path=${server.servlet.context-path}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=${server.servlet.context-path}/actuator/info

# Management properties
management.server.base-path=${server.servlet.context-path}
management.server.port=8092

# Custom application properties
## Tasks service client properties
asapp.client.tasks.base-url=http://asapp-tasks-service/asapp-tasks-service
