version: '3.8'
services:
  asapp-projects-postgres-db:
    image: 'postgres:latest'
    container_name: asapp-projects-postgres-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=projectsdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - projects-postgres-db-data:/data/db

  asapp-projects-service:
    build: .
    image: 'asapp-projects-service:0.1.0'
    container_name: asapp-projects-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - ASAPP_TASKS_SERVICE_BASE_URL=http://asapp-tasks-service:8080/asapp-tasks-service
      - DB_HOST=asapp-projects-postgres-db
      - DB_PORT=5432
      - DB_NAME=projectsdb
      - DB_USERNAME=user
      - DB_PASSWORD=secret
    depends_on:
      - asapp-projects-postgres-db

volumes:
  projects-postgres-db-data:
