# Dev configuration for asapp-discovery-service

# Spring Base Application properties
spring.devtools.livereload.enabled=true

# Management properties
management.endpoint.heapdump.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Logger properties
logging.level.com.attrigo.asapp=DEBUG
