# Spring Base Application properties
spring.application.name=asapp-discovery-service
spring.devtools.livereload.enabled=true

# Server properties
server.port=8761
server.servlet.context-path=/asapp-discovery-service

# Security properties
spring.security.user.name=user
spring.security.user.password=secret

# Eureka server properties
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://user:secret@localhost:8761/asapp-discovery-service/eureka
eureka.server.enable-self-preservation=false

# Load balancer properties
spring.cloud.loadbalancer.cache.enabled=false

# Management properties
management.endpoint.health.cache.time-to-live=30s
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.show-details=when_authorized
management.endpoint.heapdump.access=unrestricted
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true
management.metrics.tags.application=${spring.application.name}
management.server.base-path=${server.servlet.context-path}
management.server.port=8791

# Logger properties
logging.level.com.bcn.asapp.discovery=INFO
logging.level.org.springframework=INFO
